dataformCoreVersion: 3.0.30
defaultProject: ibadatatrust
defaultDataset: dataform

environments:
  - name: development
    defaultDatabase: ibadatatrust
    defaultSchema: silver_dev_${user.name}
    runAssertions: true
    tags: ["dev"]
